name: CICD pipline test without deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: terraform
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-southeast-2
      URL: <placeholder-url>

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get S3 website URL
      run: |
        echo "The app URL is $URL!"
    
