name: CICD pipline test without deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: terraform
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-southeast-2
      URL: http://parse-and-play-2.s3-website-ap-southeast-2.amazonaws.com
      BUCKET_NAME: s3://parse-and-play-2

    steps:
    - name: Checkout code...
      uses: actions/checkout@v4

    - name: Display S3 website URL
      run: echo "The app URL is $URL!"
    
    - name: Running npm install...
      run: npm install
      working-directory: frontend
      

    - name: Bulding frontend...
      run: npm run build
      working-directory: frontend
      env:
        CI: false

    - name: Uploading build files to s3...
      run: aws s3 sync ./build/ $BUCKET_NAME --delete
      working-directory: frontend
